#!/bin/bash

# security-review-orchestrator.sh
# Daily security review of the entire codebase

set -e

PROJECT_DIR="$(pwd)"
TIMESTAMP=$(date +%Y-%m-%d)
REPORT_FILE="SECURITY_REPORT_${TIMESTAMP}.md"

echo "🔒 Solarpunk Security Review - $(date) 🔒"
echo "=============================================="
echo ""

# Phase 1: Security Scan Agent
echo "🔍 Phase 1: Launching Security Scan Agent..."
echo "Reviewing codebase for security vulnerabilities..."
echo ""

claude --dangerously-skip-permissions --print "
You are the Security Scan Agent for the Solarpunk Utopia Platform.

IMPORTANT: First, read the security-reviewer-guide.md file in the project root.
This contains comprehensive security review guidelines.

YOUR TASK:
1. Read security-reviewer-guide.md to understand security review principles
2. Perform a comprehensive security review of the codebase focusing on:

   OWASP TOP 10 (ADAPTED FOR OFFLINE-FIRST WEB APPS):
   - [ ] Injection vulnerabilities (XSS, command injection)
   - [ ] Broken authentication/authorization
   - [ ] Sensitive data exposure
   - [ ] Missing input validation
   - [ ] Security misconfiguration
   - [ ] Insecure dependencies (check package.json)
   - [ ] Insufficient logging and monitoring
   - [ ] Insecure deserialization
   - [ ] Using components with known vulnerabilities
   - [ ] Insufficient API security

   TYPESCRIPT/JAVASCRIPT SPECIFIC:
   - [ ] Prototype pollution risks
   - [ ] eval() or Function() usage
   - [ ] Unsafe regular expressions (ReDoS)
   - [ ] Insecure randomness (Math.random() for security)
   - [ ] Missing Content Security Policy
   - [ ] localStorage/sessionStorage XSS vectors
   - [ ] Unsafe DOM manipulation (innerHTML with user data)

   AUTOMERGE/CRDT SPECIFIC:
   - [ ] Data validation before CRDT operations
   - [ ] Proper handling of undefined vs null
   - [ ] No sensitive data leaking through sync
   - [ ] Proper access controls on shared documents

   PRIVACY & SOLARPUNK VALUES:
   - [ ] No tracking or analytics code
   - [ ] No external API calls without user consent
   - [ ] Encryption for sensitive data
   - [ ] User data sovereignty maintained
   - [ ] No hard-coded secrets or credentials

3. Check for:
   - Hardcoded secrets, API keys, passwords
   - Unsafe file operations
   - Missing error boundaries
   - Exposed debug endpoints
   - Insecure crypto implementations
   - Race conditions in async operations
   - Missing rate limiting
   - Inadequate CORS configuration

4. Review recent git commits for security-sensitive changes

5. Generate a detailed security report in ${REPORT_FILE} with:
   - Executive summary (severity counts)
   - Detailed findings (severity, location, description, recommendation)
   - Compliance with solarpunk values
   - Dependency vulnerability scan results
   - Recommendations prioritized by risk

6. DO NOT fix any issues yet - just document them

Focus on code in src/, looking for actual vulnerabilities, not just style issues.
Be thorough but pragmatic - this is a mutual aid platform, not a banking app.
"

if [ $? -ne 0 ]; then
    echo "❌ Security scan agent failed!"
    exit 1
fi

echo ""
echo "✅ Security scan complete!"
echo ""

# Phase 2: Dependency Security Check
echo "🔍 Phase 2: Checking Dependencies..."
echo ""

# Run npm audit
echo "Running npm audit..."
npm audit --json > npm-audit-${TIMESTAMP}.json 2>&1 || true

# Display summary
if [ -f "npm-audit-${TIMESTAMP}.json" ]; then
    echo "Dependency audit saved to npm-audit-${TIMESTAMP}.json"
fi

echo ""
echo "✅ Dependency check complete!"
echo ""

# Phase 3: Critical Fixes Agent
echo "🔧 Phase 3: Launching Critical Fixes Agent..."
echo "Addressing critical and high severity findings..."
echo ""

claude --dangerously-skip-permissions --print "
You are the Security Fixes Agent for the Solarpunk Utopia Platform.

YOUR TASK:
1. Read the ${REPORT_FILE} generated by the previous agent
2. Identify CRITICAL and HIGH severity findings
3. Fix these critical issues:
   - Apply secure coding patterns from security-reviewer-guide.md
   - Ensure fixes don't break existing functionality
   - Follow the project's code style and patterns
4. Run tests after each fix (npm test)
5. Document what you fixed in SECURITY_FIXES_${TIMESTAMP}.md
6. DO NOT commit - the next agent will do that

IMPORTANT:
- Only fix CRITICAL and HIGH severity issues automatically
- For MEDIUM/LOW issues, just document them for manual review
- Test thoroughly - don't break working code
- Follow existing patterns in the codebase
- Use existing utilities (src/utils/sanitize.ts, etc.)

Start by reading ${REPORT_FILE} and prioritizing the critical findings.
"

if [ $? -ne 0 ]; then
    echo "❌ Security fixes agent failed!"
    exit 1
fi

echo ""
echo "✅ Critical fixes complete!"
echo ""

# Phase 4: Commit Agent
echo "📝 Phase 4: Launching Commit Agent..."
echo ""

claude --dangerously-skip-permissions --print "
You are the Security Commit Agent for the Solarpunk Utopia Platform.

YOUR TASK:
1. Check if there are any files modified (git status)
2. If there are security fixes:
   - Review what was changed
   - Create a descriptive commit message:
     'Security: Address [X] critical/high severity findings

     - Fixed: [specific issue 1]
     - Fixed: [specific issue 2]
     - See ${REPORT_FILE} for full details

     🔒 Security review performed $(date +%Y-%m-%d)

     🌻 Generated with [Claude Code](https://claude.com/claude-code)
     Co-Authored-By: Claude <noreply@anthropic.com>'
   - Commit the changes
   - Push to GitHub
3. If no fixes were needed:
   - Just commit the security reports with message:
     'Security: Daily security review - no critical issues found

     See ${REPORT_FILE} for details

     🔒 Security review performed $(date +%Y-%m-%d)

     🌻 Generated with [Claude Code](https://claude.com/claude-code)
     Co-Authored-By: Claude <noreply@anthropic.com>'

Always commit the security reports so we have a historical record.
"

if [ $? -ne 0 ]; then
    echo "❌ Commit agent failed!"
    exit 1
fi

echo ""
echo "✅ Security review complete!"
echo ""
echo "📊 Report saved to: ${REPORT_FILE}"
echo ""
